#!/usr/bin/env bash
# test_provider_trim_persist.sh — the per-provider TRIM knob (CMA_PROVIDER_TRIM)
# survives regeneration of a provider's .env by cma_provider_write_env.
#
# Backlog gap (v1.25.2): CMA_PROVIDER_TRIM='bare' is an opt-in per-provider knob
# read by cma_run_provider (scripts/lib.sh). It is NOT part of the models.dev
# catalog nor the alias manifest, so it is hand-set on a provider's env file.
# But cma_provider_write_env — the generator, driven by claude-providers.sh on
# `add`/re-add — OVERWRITES the whole file (`cat > $id.env`), and its own header
# says "generated by claude-providers — do not edit by hand". A re-add of the
# provider therefore DROPS the hand-added trim line: the knob silently vanishes
# and the local-model provider goes back to overflowing its context window.
#
# Contract under test (generator-level, exercises the REAL cma_provider_write_env
# — it does NOT grep lib.sh):
#   (1) Re-running cma_provider_write_env for a provider whose current .env
#       carries CMA_PROVIDER_TRIM='bare' PRESERVES that line in the rewrite.
#   (2) The preserved value still sources to exactly 'bare' (usable by the
#       wrapper's ${CMA_PROVIDER_TRIM:-} == "bare" gate).
#   (3) REGRESSION: a provider whose .env never had the knob does NOT gain a
#       spurious CMA_PROVIDER_TRIM line after regeneration.
#   (4) The generator does not seed the value from an ambient exported
#       CMA_PROVIDER_TRIM — only the on-disk value is preserved.
set -uo pipefail
TESTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$(cd "$TESTS_DIR/.." && pwd)"
source "$TESTS_DIR/lib/assert.sh"
source "$TESTS_DIR/lib/sandbox.sh"
make_sandbox
# shellcheck source=../lib.sh
source "$SCRIPTS_DIR/lib.sh"
set +e

pdir="$(cma_providers_dir)"; mkdir -p "$pdir"

# args: id keyvar transport base model fast config_dir [ctx [max_out [alias]]]
gen() {
  cma_provider_write_env "$1" TESTKEY router "http://127.0.0.1:9/v1" testmodel testmodel \
    "$SANDBOX_HOME/.claude-prov-$1" 200000 8192 "$1"
}

# ── (1)+(2): a trimmed provider re-generated keeps the knob ──────────────────
gen trimrtr
# Field state: the knob was hand-appended after generation (v1.25.2 behaviour).
printf "CMA_PROVIDER_TRIM='bare'\n" >> "$pdir/trimrtr.env"
it "PRECONDITION: the hand-set trim knob is present before regeneration"
assert_file_contains "$pdir/trimrtr.env" "CMA_PROVIDER_TRIM='bare'" "trim knob written"

# Regenerate the SAME provider (the add/re-add path both callers take).
gen trimrtr

it "(1) regeneration PRESERVES CMA_PROVIDER_TRIM='bare' in the rewritten .env"
assert_file_contains "$pdir/trimrtr.env" "CMA_PROVIDER_TRIM='bare'" "trim knob survived rewrite"

it "(2) the preserved value sources to exactly 'bare'"
val="$( ( unset CMA_PROVIDER_TRIM; set -a; . "$pdir/trimrtr.env"; set +a; printf '%s' "${CMA_PROVIDER_TRIM:-}" ) )"
assert_eq "bare" "$val" "CMA_PROVIDER_TRIM sources to bare"

# ── (3): an untrimmed provider stays untrimmed after regeneration ────────────
gen plainrtr
it "PRECONDITION: an untrimmed provider has no trim knob"
assert_file_not_contains "$pdir/plainrtr.env" "CMA_PROVIDER_TRIM" "no trim knob on plain provider"

gen plainrtr
it "(3) REGRESSION: regeneration does NOT add a spurious CMA_PROVIDER_TRIM line"
assert_file_not_contains "$pdir/plainrtr.env" "CMA_PROVIDER_TRIM" "still no trim knob after rewrite"

# ── (4): an ambient exported CMA_PROVIDER_TRIM must NOT seed the file ─────────
export CMA_PROVIDER_TRIM='bare'
gen envrtr
unset CMA_PROVIDER_TRIM
it "(4) an ambient exported CMA_PROVIDER_TRIM does NOT leak into the generated file"
assert_file_not_contains "$pdir/envrtr.env" "CMA_PROVIDER_TRIM" "ambient env var not stamped onto file"

summary
