#!/usr/bin/env python3
"""providers_generate.py — multi-alias generation from verified models.

Reads verified_models.json (output of model_verify.py) and generates
alias configurations: env files, shell aliases, and overrides.json entries.

Alias pairing strategy:
- Models sorted by score descending
- 2 models per alias (strong + fast)
- Odd count: last model used for both positions in last alias
- Single model: used for both positions
- Naming: provider (primary), provider2, provider3, etc.

Usage:
  providers_generate.py --provider <id> --verified <path> --output-dir <dir> \
    [--max-aliases 5] [--min-score 25] [--dry-run]

Output: JSON manifest of generated aliases + env files on disk.
"""
import argparse
import json
import os
import sys
from datetime import datetime, timezone


def _parse_limit(s):
    """Coerce a limit arg (int, empty string, or the literal 'null') to int or None."""
    if s is None or s == "" or s == "null":
        return None
    try:
        return int(s)
    except (ValueError, TypeError):
        return None


def load_verified(path):
    """Load verified models from model_verify.py output."""
    with open(path) as f:
        return json.load(f)


def pair_models(models, max_aliases=5, min_score=25):
    """Pair verified models into alias groups of 2.

    Returns list of alias specs:
    [{"alias_suffix": "", "strong": model, "fast": model, "index": 1}, ...]
    """
    # Filter to verified models above min score
    verified = [m for m in models if m.get("verified") and m.get("score", 0) >= min_score]

    if not verified:
        return []

    # Sort by score descending
    verified.sort(key=lambda m: m.get("score", 0), reverse=True)

    aliases = []
    i = 0
    while i < len(verified) and len(aliases) < max_aliases:
        strong = verified[i]
        if i + 1 < len(verified):
            fast = verified[i + 1]
        else:
            # Odd count — reuse last model for both positions
            fast = strong

        idx = len(aliases) + 1
        suffix = "" if idx == 1 else str(idx)

        aliases.append({
            "alias_suffix": suffix,
            "strong": strong,
            "fast": fast,
            "index": idx,
        })
        i += 2

    return aliases


def generate_env_content(provider_id, alias_suffix, key_var, transport, base_url, strong_model, fast_model, config_dir, context_limit=None, max_output=None):
    """Generate env file content for a provider alias."""
    def q(s):
        # POSIX single-quote escaping (close, escaped-quote, reopen) so a catalog
        # value containing a quote can't break — or inject into — the generated
        # .env when cma_run_provider later `source`s it. Mirrors lib.sh _cma_q.
        return "''" if not s else "'" + s.replace("'", "'\\''") + "'"
    # Emit numeric limits as plain integers (no quotes needed, but q("") is safe).
    ctx = "" if context_limit is None else str(int(context_limit))
    out = "" if max_output is None else str(int(max_output))
    return f"""# generated by claude-providers — non-secret. Do not edit by hand.
# Secrets are NEVER stored here; the key is read from the keys file at launch.
CMA_PROVIDER_ID={q(provider_id)}
CMA_PROVIDER_ALIAS_SUFFIX={q(alias_suffix)}
CMA_PROVIDER_KEYVAR={q(key_var)}
CMA_PROVIDER_TRANSPORT={q(transport)}
CMA_PROVIDER_BASE_URL={q(base_url)}
CMA_PROVIDER_MODEL={q(strong_model)}
CMA_PROVIDER_FAST_MODEL={q(fast_model)}
CMA_PROVIDER_CONFIG_DIR={q(config_dir)}
# Context-window limits from the models.dev catalog for the selected strong model.
# Consumer: cma_run_provider exports CLAUDE_CODE_MAX_OUTPUT_TOKENS from
# CMA_PROVIDER_MAX_OUTPUT to prevent overshooting the provider's real limit.
CMA_PROVIDER_CONTEXT_LIMIT={q(ctx)}
CMA_PROVIDER_MAX_OUTPUT={q(out)}
"""


def generate_manifest(provider_id, aliases, key_var, transport, base_url, account_prefix, home, context_limit=None, max_output=None):
    """Generate the full manifest for a provider's aliases."""
    manifest = {
        "provider_id": provider_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "alias_count": len(aliases),
        "aliases": [],
    }

    for alias in aliases:
        suffix = alias["alias_suffix"]
        strong_id = alias["strong"]["model_id"]
        fast_id = alias["fast"]["model_id"]
        alias_name = f"{provider_id}{suffix}"
        config_dir = os.path.join(home, f"{account_prefix}prov-{alias_name}")

        manifest["aliases"].append({
            "alias_name": alias_name,
            "provider_id": provider_id,
            "alias_suffix": suffix,
            "strong_model": strong_id,
            "fast_model": fast_id,
            "strong_score": alias["strong"]["score"],
            "fast_score": alias["fast"]["score"],
            "transport": transport,
            "base_url": base_url,
            "config_dir": config_dir,
            "key_var": key_var,
            "context_limit": context_limit,
            "max_output": max_output,
        })

    return manifest


def write_env_files(manifest, output_dir):
    """Write env files for each alias."""
    os.makedirs(output_dir, exist_ok=True)
    written = []

    for alias in manifest["aliases"]:
        env_content = generate_env_content(
            provider_id=alias["provider_id"],
            alias_suffix=alias["alias_suffix"],
            key_var=alias["key_var"],
            transport=alias["transport"],
            base_url=alias["base_url"],
            strong_model=alias["strong_model"],
            fast_model=alias["fast_model"],
            config_dir=alias["config_dir"],
            context_limit=alias.get("context_limit"),
            max_output=alias.get("max_output"),
        )
        env_path = os.path.join(output_dir, f"{alias['alias_name']}.env")
        with open(env_path, "w") as f:
            f.write(env_content)
        written.append(env_path)

    return written


def generate_alias_lines(manifest):
    """Generate shell alias lines for the alias file."""
    lines = []
    for alias in manifest["aliases"]:
        name = alias["alias_name"]
        # The alias invokes cma_run_provider with the suffixed provider ID
        lines.append(f'alias {name}="cma_run_provider {name}"')
    return lines


def generate_overrides(manifest):
    """Generate overrides.json entries for all aliases."""
    overrides = {}
    for alias in manifest["aliases"]:
        name = alias["alias_name"]
        overrides[name] = {
            "strong_model": alias["strong_model"],
            "fast_model": alias["fast_model"],
        }
        if alias["alias_suffix"]:  # Non-primary aliases
            overrides[name]["transport"] = alias["transport"]
            overrides[name]["base_url"] = alias["base_url"]
    return overrides


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate multi-alias configurations from verified models")
    ap.add_argument("--provider", required=True, help="Provider ID")
    ap.add_argument("--verified", required=True, help="Path to verified_models.json")
    ap.add_argument("--output-dir", default="", help="Output directory for env files")
    ap.add_argument("--max-aliases", type=int, default=5, help="Maximum aliases per provider")
    ap.add_argument("--min-score", type=int, default=25, help="Minimum score to include a model")
    ap.add_argument("--key-var", default="", help="API key variable name (overrides catalog)")
    ap.add_argument("--transport", default="router", help="Transport type (native/router)")
    ap.add_argument("--base-url", default="", help="API base URL (overrides catalog)")
    ap.add_argument("--account-prefix", default=".claude-", help="Account dir prefix")
    ap.add_argument("--home", default=os.path.expanduser("~"), help="Home directory")
    ap.add_argument("--context-limit", default="", help="Input context window size in tokens (from catalog)")
    ap.add_argument("--max-output", default="", help="Max output tokens (from catalog)")
    ap.add_argument("--dry-run", action="store_true", help="Print without writing")
    ap.add_argument("--json", action="store_true", help="Output manifest as JSON to stdout")
    args = ap.parse_args(argv)

    # Load verified models
    verified_data = load_verified(args.verified)
    models = verified_data.get("models", [])

    # Get endpoint from verified data if not specified
    base_url = args.base_url or verified_data.get("endpoint", "")
    key_var = args.key_var or f"{args.provider.upper().replace('-', '_')}_API_KEY"

    # Pair models into aliases
    aliases = pair_models(models, max_aliases=args.max_aliases, min_score=args.min_score)

    if not aliases:
        print(f"No verified models above score {args.min_score} for {args.provider}", file=sys.stderr)
        return 1

    # Generate manifest
    manifest = generate_manifest(
        provider_id=args.provider,
        aliases=aliases,
        key_var=key_var,
        transport=args.transport,
        base_url=base_url,
        account_prefix=args.account_prefix,
        home=args.home,
        context_limit=_parse_limit(args.context_limit),
        max_output=_parse_limit(args.max_output),
    )

    if args.json:
        print(json.dumps(manifest, indent=2))
        return 0

    if args.dry_run:
        for alias in manifest["aliases"]:
            print(f"  alias {alias['alias_name']}: strong={alias['strong_model']} (score={alias['strong_score']}), fast={alias['fast_model']} (score={alias['fast_score']})")
        return 0

    # Write env files
    if args.output_dir:
        written = write_env_files(manifest, args.output_dir)
        for path in written:
            print(f"  wrote: {path}", file=sys.stderr)

    # Output manifest
    print(json.dumps(manifest, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
